name: Health System CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-24.04  # Explicitly use the new Ubuntu image

    permissions:
      contents: read
      packages: read

    steps:
      # Step 1: Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Python environment
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      # Step 3: Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      # Step 4: Run flake8 linting
      - name: Run flake8 linting
        run: |
          pip install flake8
          flake8 .
        continue-on-error: true

      # Step 5: Generate flake8 report
      - name: Generate flake8 report
        run: |
          pip install flake8
          flake8 . > flake8-report.txt || true
        continue-on-error: true

      # Step 6: Upload artifact
      - name: Upload flake8 report artifact
        uses: actions/upload-artifact@v4  # Updated version
        with:
          name: flake8-report
          path: flake8-report.txt

      # Step 7: Run unit tests
      - name: Run tests
        run: |
          if [ -d tests ]; then python -m unittest discover tests; fi
